import { open, board, wave, stroke, inked, works, ready } from './h.mjs';
const t = await open('desktop');
const { page } = t;
const b = await board(page);
await page.evaluate(() => { CL.pizarra.current._test.selectTool('fibra'); CL.pizarra.current._test.selectSize(3); });
await stroke(page, wave(b, 0.3), { steps: 20 });
await page.waitForTimeout(2000);
console.log('ink1', await inked(page));
await stroke(page, wave(b, 0.6), { steps: 20, release: false });
console.log('live', await page.evaluate(() => [...document.querySelectorAll('.pz-live')].map((c) => !c.hidden)));
await page.evaluate(() => { window.__log = []; const o = CL.db.works.save; CL.db.works.save = async (w) => { window.__log.push('save ' + w.status + ' ' + (w.paint && w.paint.size)); return o(w); }; });
await page.evaluate(() => CL.router.go('inicio'));
await page.waitForTimeout(1500);
console.log(await page.evaluate(() => window.__log));
await page.mouse.up();
await page.evaluate(() => CL.router.go('pizarra'));
await ready(page);
console.log('ink back', await inked(page), await works(page));
console.log(t.errors);
await t.close();
