// Revisión QA 2 — compu: espacio + arrastre y botón del medio para mover, Ctrl+Z / Ctrl+Y, +/-/0; foco en botones.
import { launch, appUrl, shot } from '../lib.mjs';
import { ready, P, paintAt, filterErrors } from '../review-colorear/common.mjs';
const t = await launch({ size: 'desktop' });
const { page } = t;
await page.goto(appUrl('colorear/robot'));
await ready(page);
await paintAt(t, 0.5, 0.45);
const v = () => page.evaluate(() => { const s = CL.coloring.screen.view; return { k: +s.k.toFixed(2), tx: Math.round(s.tx), ty: Math.round(s.ty) }; });
await page.keyboard.press('+'); await page.waitForTimeout(300); await page.keyboard.press('+'); await page.waitForTimeout(300);
console.log('tras + +', JSON.stringify(await v()));
const [cx, cy] = await P(page, 0.5, 0.5);
const h0 = await page.evaluate(() => CL.coloring.screen.painter.historyLength);
await page.keyboard.down('Space');
await page.mouse.move(cx, cy); await page.mouse.down(); await page.mouse.move(cx + 200, cy + 120, { steps: 8 }); await page.mouse.up();
await page.keyboard.up('Space');
console.log('espacio+arrastre', JSON.stringify(await v()), 'pasos nuevos', (await page.evaluate(() => CL.coloring.screen.painter.historyLength)) - h0);
await page.mouse.move(cx, cy); await page.mouse.down({ button: 'middle' }); await page.mouse.move(cx - 300, cy - 100, { steps: 8 }); await page.mouse.up({ button: 'middle' });
console.log('botón medio', JSON.stringify(await v()));
await page.keyboard.press('Control+z'); await page.waitForTimeout(200);
console.log('ctrl+z puede deshacer?', await page.evaluate(() => CL.coloring.screen.painter.canUndo), 'rehacer?', await page.evaluate(() => CL.coloring.screen.painter.canRedo));
await page.keyboard.press('Control+y'); await page.waitForTimeout(200);
console.log('ctrl+y rehacer?', await page.evaluate(() => CL.coloring.screen.painter.canRedo));
await page.keyboard.press('0'); await page.waitForTimeout(300);
console.log('0', JSON.stringify(await v()));
// Foco con Tab en "Pincel" y activar con espacio / Enter
await page.focus('[aria-label="Pincel"]');
await page.keyboard.press('Space'); await page.waitForTimeout(150);
console.log('espacio sobre botón Pincel activa?', await page.evaluate(() => CL.coloring.screen.st.tool));
await page.focus('[aria-label="Pincel"]');
await page.keyboard.press('Enter'); await page.waitForTimeout(150);
console.log('Enter sobre botón Pincel activa?', await page.evaluate(() => CL.coloring.screen.st.tool));
console.log(JSON.stringify(filterErrors(t.errors)));
await t.close();
