import { chromium } from 'playwright-core';
import { pathToFileURL } from 'node:url';
import fs from 'node:fs';
const [,, src, x, y, w, h, out, scale='2'] = process.argv;
const b = await chromium.launch({ channel: 'msedge' });
const p = await b.newPage();
const data = 'data:image/png;base64,' + fs.readFileSync(src).toString('base64');
const url = await p.evaluate(async ({data,x,y,w,h,s}) => { const i = new Image(); i.src = data; await i.decode(); const c = document.createElement('canvas'); c.width = w*s; c.height = h*s; const g = c.getContext('2d'); g.imageSmoothingEnabled = false; g.drawImage(i, x, y, w, h, 0, 0, w*s, h*s); return c.toDataURL(); }, {data, x:+x, y:+y, w:+w, h:+h, s:+scale});
fs.writeFileSync(out, Buffer.from(url.split(',')[1], 'base64'));
await b.close();
