// Depuración: qué pasa al cerrar la pestaña 100 ms después de salir con "inicio".
import { launch, appUrl, multiStroke, rect, SHOTS } from '../lib.mjs';
import path from 'node:path';
import fs from 'node:fs';
const size = process.argv[2] || 'tablet';
const W = +(process.argv[3] || 100);
const prof = path.join(SHOTS, 'neon', 'fix', '_perfil-dbg-' + size);
fs.rmSync(prof, { recursive: true, force: true });
let t = await launch({ size, persistent: prof });
const logs = [];
t.page.on('console', (m) => logs.push(m.text()));
await t.page.addInitScript(() => {
  const T0 = performance.now();
  const L = (...a) => console.log('[' + Math.round(performance.now() - T0) + ']', ...a);
  const si = Storage.prototype.setItem, ri = Storage.prototype.removeItem;
  Storage.prototype.setItem = function (k, v) { if (k.includes('neonRescate')) L('setItem', k, String(v).length); return si.call(this, k, v); };
  Storage.prototype.removeItem = function (k) { if (k.includes('neonRescate')) L('removeItem', k); return ri.call(this, k); };
  const put = IDBObjectStore.prototype.put;
  IDBObjectStore.prototype.put = function (v, ...a) { if (v && v.kind === 'neon') L('put', v.updatedAt, v.paint && v.paint.size); const q = put.call(this, v, ...a); this.transaction.addEventListener('complete', () => L('complete', v && v.updatedAt)); return q; };
  document.addEventListener('visibilitychange', () => L('visibility', document.visibilityState));
  window.addEventListener('pagehide', () => L('pagehide'));
});
await t.page.goto(appUrl('neon'));
await t.page.waitForFunction(() => CL.neon && CL.neon.debug && CL.neon.debug.ready);
const r = await rect(t.page, '.neon-stage');
const line = (fy) => { const p = []; for (let i = 0; i <= 30; i++) p.push([r.x + r.width * (0.1 + 0.8 * i / 30), r.y + r.height * (fy + 0.1 * Math.sin(i / 2))]); return p; };
await multiStroke(t.page, [line(0.3)], { steps: 30, delay: 5 });
await t.page.waitForTimeout(2000);
await t.page.evaluate(() => console.log('--- segundo trazo'));
await multiStroke(t.page, [line(0.6)], { steps: 30, delay: 5 });
await t.page.locator('.screen--neon .btn-home').click();
await t.page.evaluate(() => console.log('--- en inicio'));
await t.page.waitForTimeout(W);
await t.page.evaluate(() => console.log('--- cierro'));
await t.page.close({ runBeforeUnload: true });
await new Promise((res) => setTimeout(res, 300));
await t.close();
console.log(logs.join('\n'));
t = await launch({ size, persistent: prof });
await t.page.goto(appUrl('inicio'));
await t.page.waitForTimeout(500);
console.log('rescate al reabrir:', await t.page.evaluate(() => localStorage.getItem('colorinche.neonRescate.info')));
console.log('obras', await t.page.evaluate(async () => (await CL.db.works.list({ kind: 'neon' })).map((w) => [w.updatedAt, w.paint.size])));
await t.close();
