import { launch, appUrl, multiStroke, rect, SHOTS } from '../lib.mjs';
import path from 'node:path'; import fs from 'node:fs';
const prof = path.join(SHOTS, 'neon', '_perfil-exp2'); fs.rmSync(prof, { recursive: true, force: true });
const t = await launch({ size: 'tablet', persistent: prof });
const { page } = t;
page.on('console', (m) => console.log('  [consola]', m.type(), m.text()));
await page.goto(appUrl('neon'));
await page.waitForFunction(() => CL.neon && CL.neon.debug && CL.neon.debug.ready);
const r = await rect(page, '.neon-stage');
await multiStroke(page, [[[r.x + 100, r.y + 100], [r.x + 400, r.y + 200]]], { steps: 10 });
await page.waitForTimeout(50);
console.log(await page.evaluate(async () => {
  const p = CL.neon.debug.pending;
  const t0 = performance.now();
  const res = CL.router.flush();
  const t1 = performance.now() - t0;
  await new Promise((r) => setTimeout(r, 300));
  return { p, t1, after: CL.neon.debug.pending, n: (await CL.db.works.list({ kind: 'neon' })).length };
}));
await t.close();
