import { launch, appUrl, multiStroke, rect } from '../lib.mjs';
const t = await launch({ size: 'tablet' });
const { page } = t;
await page.goto(appUrl(process.argv[2] || 'neon'));
await page.waitForTimeout(1500);
const m = async (label) => console.log(label, await page.evaluate(async () => {
  const t0 = performance.now();
  const idle = await new Promise((r) => requestIdleCallback((d) => r(Math.round(performance.now() - t0)), { timeout: 3000 }));
  let n = 0; const orig = window.requestAnimationFrame; window.requestAnimationFrame = (f) => { n++; return orig(f); };
  await new Promise((r) => setTimeout(r, 500));
  window.requestAnimationFrame = orig;
  const c = CL.util.canvas(1000, 1000); c.getContext('2d').fillRect(0, 0, 500, 500);
  const t1 = performance.now(); await CL.util.canvasToBlob(c);
  return { idle, raf: n, toBlob: Math.round(performance.now() - t1), ac: CL.sound.ctx && CL.sound.ctx.state, anims: document.getAnimations().filter(a=>a.playState==='running').length };
}));
await m('antes');
const r = await rect(page, '.screen');
await page.mouse.move(r.x + 400, r.y + 300); await page.mouse.down(); await page.mouse.move(r.x + 500, r.y + 400, { steps: 10 }); await page.mouse.up();
await page.waitForTimeout(3000);
await m('tras mouse');
await t.close();
