// Revisión (rv): catálogo → vaca → pintar → ¡Terminé! → galería → "atrás". ¿Qué ve el chico?
import { launch, appUrl, shot } from '../../lib.mjs';
import { ok, clean } from './r1-lib.mjs';
const t = await launch({ size: 'tablet' });
const { page } = t;
await page.goto(appUrl('inicio'));
await page.waitForTimeout(800);
await page.evaluate(() => CL.router.go('dibujos'));
await page.waitForTimeout(1200);
await page.evaluate(() => CL.router.go('colorear/vaca'));
await page.waitForTimeout(2800);
const bb = await page.locator('.cl-board').boundingBox();
await page.mouse.click(bb.x + bb.width * 0.55, bb.y + bb.height * 0.5);
await page.waitForTimeout(500);
await page.locator('.cl-done').click();
await page.waitForFunction(() => location.hash.startsWith('#obras/'), null, { timeout: 15000 });
await page.waitForTimeout(1500);
await page.evaluate(() => history.back());
await page.waitForTimeout(3000);
const h = await page.evaluate(() => location.hash);
await shot(page, 'galeria/c1/termine-atras-tablet');
const n = await page.evaluate(async () => (await CL.db.works.list()).map((w) => w.status));
console.log('atrás tras ¡Terminé! →', h, 'obras en la base:', JSON.stringify(n));
ok(clean(t.errors).length === 0, 'sin errores');
await t.close();
